version: '3.8'
services:
  fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./opt:/opt/processmaker
      - ./php-fpm/processmaker.conf:/usr/local/etc/php-fpm.d/processmaker.conf
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./shared:/opt/processmaker/shared
      - sock:/var/run/php-fpm
    links:
      - mysql
    networks:
      - default
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 5555:80
    volumes:
      - ./opt:/opt/processmaker
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/processmaker.conf:/etc/nginx/conf.d/processmaker.conf
      - sock:/var/run/php-fpm
      - ./log/nginx:/var/log/nginx
    extra_hosts:
      processmaker357.local: 127.0.0.1
    networks:
      - default
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123789
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123789
      - MYSQL_DATABASE=processmaker
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - default
volumes:
  sock: null
networks:
   default: 

